#!/usr/bin/env python3
import os
from pathlib import Path
import re

# Root directory under src where all your dataset files live
ROOT = Path("src/dataset/o3_mini")

# Directory where diff files must be removed (full dataset root)
DATASET_ROOT = Path(
    "/home/ikqnm/PycharmProjects/rudra_sandbox/rudra_big/rudra_big/src/dataset/"
)

def delete_diff_files():
    """
    Delete any file named fixed_diff.rs or vulnerable_diff.rs.
    inside DATASET_ROOT recursively.
    """
    removed = 0
    for path in DATASET_ROOT.rglob("*"):
        if path.is_file() and path.name in ("fixed_diff.rs", "vulnerable_diff.rs", "demo_test.rs", "oracle.rs"):
            print(f"[DELETE] Removing {path}")
            path.unlink()
            removed += 1

    print(f"[CLEANUP] Total removed diff files: {removed}")


def is_rust_file(path: Path) -> bool:
    return path.is_file() and path.suffix == ".rs" and path.name != "mod.rs"


def make_module_name(rel_path: Path) -> str:
    """
    Convert a path like 'data_generation/CWE-020/pair1.rs'
    into a Rust-safe module name like:
        data_generation_cwe_020_pair1
    """
    stem_path = rel_path.with_suffix("")
    parts = list(stem_path.parts)
    joined = "_".join(parts)
    joined = re.sub(r"[^a-zA-Z0-9_]", "_", joined)
    joined = joined.lower()

    if re.match(r"^[0-9]", joined):
        joined = "m_" + joined

    if not joined:
        joined = "m_generated"

    return joined


def main():
    # First step: delete diff files
    delete_diff_files()

    project_root = Path(__file__).parent
    root_dir = project_root / ROOT

    if not root_dir.exists():
        raise SystemExit(f"Root directory does not exist: {root_dir}")

    rs_files = []
    for path in root_dir.rglob("*.rs"):
        if is_rust_file(path):
            rs_files.append(path)

    rs_files.sort()

    mod_rs_path = root_dir / "mod.rs"
    print(f"\nGenerating {mod_rs_path} for {len(rs_files)} Rust files...")

    lines = []
    lines.append("// AUTO-GENERATED BY gen_mods.py")
    lines.append("// Do not edit manually; re-run the script after changing dataset files.\n")

    for path in rs_files:
        rel = path.relative_to(root_dir).as_posix()
        mod_name = make_module_name(path.relative_to(root_dir))
        lines.append(f'#[path = "{rel}"]')
        lines.append(f"pub mod {mod_name};\n")

    mod_rs_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"[DONE] Written: {mod_rs_path}")


if __name__ == "__main__":
    main()

